name: Build macOS .dmg

on:
  push:
    branches:
      - with-tools-macos-subs
  workflow_dispatch:

jobs:
  build-macos:
    runs-on: macos-latest

    steps:
      - name: ğŸ”„ Checkout code
        uses: actions/checkout@v3

      - name: â˜• Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '21'

      - name: ğŸ§¼ Make mac tools & gradlew executable
        run: |
          chmod +x gradlew
#          chmod +x src/main/jpackage/tools/mac/yt-dlp_macos
#          chmod +x src/main/jpackage/tools/mac/ffmpeg
#          chmod +x src/main/jpackage/tools/mac/ffprobe


      - name: Build app
        run: ./gradlew jpackage

#      - name: âš™ï¸ Build macOS .dmg with Gradle
#        run: ./gradlew jpackage

      - name: ğŸ“¦ Upload .dmg artifact
        uses: actions/upload-artifact@v4
        with:
          name: ContentLaundry
          path: build/jpackage/ContentLaundry-1.0.3.dmg
