name: Build macOS .dmg

on:
  push:
    branches:
#      - build-macOS
      - main-winOS
  workflow_dispatch:

jobs:
  build-macos:
    runs-on: macos-latest

    steps:
      - name: ğŸ”„ Checkout code
        uses: actions/checkout@v3

      - name: â˜• Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '21'

      - name: ğŸ§¼ Set gradlew executable privileges
        run: chmod +x gradlew

      - name: âš™ï¸ Build app
        run: ./gradlew jpackage

#      - name: âš™ï¸ Build macOS .dmg with Gradle
#        run: ./gradlew jpackage

      - name: ğŸ“¦ Upload .dmg artifact
        uses: actions/upload-artifact@v4
        with:
          name: ContentLaundry-1.2.14
          path: build/jpackage/*.dmg
